### ISSUE TITLE
getApplist triggers error message in sense client

### ISSUE THREAD

**Issue by axelssonHakan** [stefanwalther/sense-extension-utils#6]
https://github.com/stefanwalther/sense-extension-utils/blob/master/src/pp-helper.js#L23

Using `qlik.getAppList` will create a "transient" app (+ socket) for getting the appList and then that socket is closed a error message (modal window) is shown in the client.

changing `qlik.getAppList` >> `app.global.getAppList` will solve this issue

**Comment by rjriel** [comment]
This should be fixed in e45da2e64c6af0ef070c21ea66e39c22fcf78697 and can probably be closed
